[package]
name = "instant-karma"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ik"
path = "src/main.rs"

[dependencies]
tide = "0.15.0"
once_cell = "1.5.2"
uuid = { version="0.8.1", features=["serde", "v4"]}
async-std = { version="1.7.0", features=["attributes"]}
structopt = "0.3.20"

toml = "0.5.7"
serde = "1.0.117"
async-ctrlc = "1.2.0"
