[package]
name = "instant-karma"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ik"
path = "src/main.rs"

[dependencies]
async-channel = "1.6.1"
async-ctrlc = "1.2.0"
async-std = {version="1.10.0", features=["attributes"]}
html-escape = "0.2.9"
notify = "4.0.17"
once_cell = "1.8.0"
pulldown-cmark = {version = "0.8.0", default-features = false }
serde = "1.0.131"
structopt = "0.3.25"
tide = "0.16.0"
toml = "0.5.8"
uuid = {version="0.8.2", features=["serde", "v4"]}
log = "0.4.14"
