[package]
name = "instant-karma"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ik"
path = "src/main.rs"

[dependencies]
tide = "0.16.0"
once_cell = "1.5.2"
uuid = { version="0.8.2", features=["serde", "v4"]}
async-std = { version="1.9.0", features=["attributes"]}
structopt = "0.3.21"

toml = "0.5.8"
serde = "1.0.123"
async-ctrlc = "1.2.0"
html-escape = "0.2.6"
pulldown-cmark = { version = "0.8.0", default-features = false }
