[package]
name = "instant-karma"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ik"
path = "src/main.rs"

[dependencies]
async-channel = "1.6.1"
async-ctrlc = "1.2.0"
async-std = {version="1.11.0", features=["attributes"]}
html-escape = "0.2.11"
notify = "4.0.17"
once_cell = "1.10.0"
pulldown-cmark = {version = "0.9.1", default-features = false }
serde = "1.0.137"
structopt = "0.3.26"
tide = "0.16.0"
toml = "0.5.9"
uuid = {version="1.0.0", features=["serde", "v4"]}
log = "0.4.17"
